module Record63 where

data Record63 = Record63
  { field1 :: Int
  , field2 :: Int
  , field3 :: Int
  , field4 :: Int
  , field5 :: Int
  , field6 :: Int
  , field7 :: Int
  , field8 :: Int
  , field9 :: Int
  , field10 :: Int
  , field11 :: Int
  , field12 :: Int
  , field13 :: Int
  , field14 :: Int
  , field15 :: Int
  , field16 :: Int
  , field17 :: Int
  , field18 :: Int
  , field19 :: Int
  , field20 :: Int
  , field21 :: Int
  , field22 :: Int
  , field23 :: Int
  , field24 :: Int
  , field25 :: Int
  , field26 :: Int
  , field27 :: Int
  , field28 :: Int
  , field29 :: Int
  , field30 :: Int
  , field31 :: Int
  , field32 :: Int
  , field33 :: Int
  , field34 :: Int
  , field35 :: Int
  , field36 :: Int
  , field37 :: Int
  , field38 :: Int
  , field39 :: Int
  , field40 :: Int
  , field41 :: Int
  , field42 :: Int
  , field43 :: Int
  , field44 :: Int
  , field45 :: Int
  , field46 :: Int
  , field47 :: Int
  , field48 :: Int
  , field49 :: Int
  , field50 :: Int
  , field51 :: Int
  , field52 :: Int
  , field53 :: Int
  , field54 :: Int
  , field55 :: Int
  , field56 :: Int
  , field57 :: Int
  , field58 :: Int
  , field59 :: Int
  , field60 :: Int
  , field61 :: Int
  , field62 :: Int
  , field63 :: Int
  }
